[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "googleOInfTravelContainer"
version = "0.1.0"
description = "AgentCore Runtime Application using Google ADK (Container build)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp-proto-http",
    "openinference-instrumentation-google-adk",
    "aws-opentelemetry-distro >= 0.17.1",
    "google-adk >= 1.17.0",
    "bedrock-agentcore >= 1.0.3",
    "botocore[crt] >= 1.35.0",

]

[tool.hatch.build.targets.wheel]
packages = ["."]

[dependency-groups]
dev = [
    "bedrock-agentcore-starter-toolkit>=0.3.9",
]
